training:
  sde: vesde
  n_iters: 2_000_000
  batch_size: 2 # used to be 8
  snapshot_freq: 10000
  log_freq: 50
  eval_freq: 100
  snapshot_freq_for_preemption: 10_000
  snapshot_sampling: True
  epochs: 1000

sampling:
  n_steps_each: 1
  noise_removal: True
  probability_flow: False
  snr: 0.17
  method: pc
  predictor: reverse_diffusion
  corrector: langevin

data:
  dataset_path: "./../raw-pdbs"        # "./pdbs"  for local
  caption_path: "./../caption-pdbs/abstract.json"    #"./ann.json"  for local
  processed_dataset_path: "./../processed-all-pdb-dicts"
  min_res_num: 40
  max_res_num: 256 # used to be 128
  num_channels: 5

model:
  condition: [] # ["length"]
  sigma_max: 100.
  sigma_min: 0.01
  num_scales: 2000
  beta_min: 0.1
  beta_max: 20.
  dropout: 0.1
  embedding_type: positional
  name: ncsnpp
  scale_by_sigma: True
  ema_rate: 0.999
  normalization: GroupNorm
  nonlinearity: swish
  nf: 256 # used to be 128
  ch_mult: [1, 1, 2, 2, 2, 2,]
  num_res_blocks: 2
  attn_resolutions: [8, 16, 32] #[8, 16, 32]
  resamp_with_conv: True
  skip_rescale: True
  resblock_type: biggan
  attention_type: ddpm
  init_scale: 0.
  fourier_scale: 16
  conv_size: 3
  n_heads: 8
  context_dim: 4096 # 4096 for vicuna-7b, 5120 for vicuna-13b

optim:
  weight_decay: 0
  optimizer: Adam
  lr: 1.e-4
  beta1: 0.9
  eps: 1.e-8
  warmup: 5000
  grad_clip: 1.

seed: 42
device: cuda


